---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false

tabs:
  - name: ">_ control"
    url: /wetty
  - name: ">_ node01"
    url: /wetty_node01
  - name: ">_ node02"
    url: /wetty_node02
  - name: ">_ node03"
    url: /wetty_node03
  - name: Cloud
    url: /cloud
